# Generated by Django 2.2.5 on 2020-02-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200213_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-create_at',), 'verbose_name': '书籍管理', 'verbose_name_plural': '书籍管理'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-create_at',), 'verbose_name': '分类管理', 'verbose_name_plural': '分类管理'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-create_at',), 'verbose_name': '公告管理', 'verbose_name_plural': '公告管理'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-create_at',), 'verbose_name': '订单管理', 'verbose_name_plural': '订单管理'},
        ),
    ]
